//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlainTextFilesEncryptionPortal.FileServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileServiceReference.IFileService")]
    public interface IFileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/SendData", ReplyAction="http://tempuri.org/IFileService/SendDataResponse")]
        void SendData(string fileName, byte[] data, string hash, byte[] sign, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/SendData", ReplyAction="http://tempuri.org/IFileService/SendDataResponse")]
        System.Threading.Tasks.Task SendDataAsync(string fileName, byte[] data, string hash, byte[] sign, string key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileServiceChannel : PlainTextFilesEncryptionPortal.FileServiceReference.IFileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileServiceClient : System.ServiceModel.ClientBase<PlainTextFilesEncryptionPortal.FileServiceReference.IFileService>, PlainTextFilesEncryptionPortal.FileServiceReference.IFileService {
        
        public FileServiceClient() {
        }
        
        public FileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendData(string fileName, byte[] data, string hash, byte[] sign, string key) {
            base.Channel.SendData(fileName, data, hash, sign, key);
        }
        
        public System.Threading.Tasks.Task SendDataAsync(string fileName, byte[] data, string hash, byte[] sign, string key) {
            return base.Channel.SendDataAsync(fileName, data, hash, sign, key);
        }
    }
}
